<option value='' selected>Mês</option>
<OPTION value='1'>1</option>
<OPTION value='2'>2</option>
<OPTION value='3'>3</option>
<OPTION value='4'>4</option>
<OPTION value='5'>5</option>
<OPTION value='6'>6</option>
<OPTION value='7'>7</option>
<OPTION value='8'>8</option>
<OPTION value='9'>9</option>
<OPTION value='10'>10</option>
<OPTION value='11'>11</option>
<OPTION value='12'>12</option>