<option value=''>--------------------------------</option>
<option value='1 - Banco do Brasil S.A.'>1 - Banco do Brasil S.A.</option>
<option value='3 - Banco da Amazônia S.A.'>3 - Banco da Amazônia S.A.</option>
<option value='4 - Banco do Nordeste do Brasil S.A.'>4 - Banco do Nordeste do Brasil S.A.</option>
<option value='21 - BANESTES S.A.  Banco do Estado do Espírito Santo'>21 - BANESTES S.A. Banco do Estado do Espírito Santo</option>
<option value='24 - Banco de Pernambuco S.A. - BANDEPE'>24 - Banco de Pernambuco S.A. - BANDEPE</option>
<option value='25 - Banco Alfa S.A.'>25 - Banco Alfa S.A.</option>
<option value='27 - Banco do Estado de Santa Catarina S.A.'>27 - Banco do Estado de Santa Catarina S.A.</option>
<option value='29 - Banco Banerj S.A.'>29 - Banco Banerj S.A.</option>
<option value='31 - Banco Beg S.A.'>31 - Banco Beg S.A.</option>
<option value='33 - Banco Santander S.A.'>33 - Banco Santander S.A.</option>
<option value='36 - Banco Bradesco BBI S.A.'>36 - Banco Bradesco BBI S.A.</option>
<option value='37 - Banco do Estado do Pará S.A.'>37 - Banco do Estado do Pará S.A.</option>
<option value='38 - Banco Banestado S.A.'>38 - Banco Banestado S.A.</option>
<option value='39 - Banco do Estado do Piauí S.A. - BEP'>39 - Banco do Estado do Piauí S.A. - BEP</option>
<option value='40 - Banco Cargill S.A.'>40 - Banco Cargill S.A.</option>
<option value='41 - Banco do Estado do Rio Grande do Sul S.A.'>41 - Banco do Estado do Rio Grande do Sul S.A.</option>
<option value='44 - Banco BVA S.A.'>44 - Banco BVA S.A.</option>
<option value='45 - Banco Opportunity S.A.'>45 - Banco Opportunity S.A.</option>
<option value='47 - Banco do Estado de Sergipe S.A.'>47 - Banco do Estado de Sergipe S.A.</option>
<option value='62 - Hipercard Banco Múltiplo S.A.'>62 - Hipercard Banco Múltiplo S.A.</option>
<option value='63 - Banco Ibi S.A.  Banco Múltiplo'>63 - Banco Ibi S.A. Banco Múltiplo</option>
<option value='64 - Goldman Sachs do Brasil Banco Múltiplo S.A.'>64 - Goldman Sachs do Brasil Banco Múltiplo S.A.</option>
<option value='65 - Lemon Bank Banco Múltiplo S.A.'>65 - Lemon Bank Banco Múltiplo S.A.</option>
<option value='66 - Banco Morgan Stanley S.A.'>66 - Banco Morgan Stanley S.A.</option>
<option value='69 - BPN Brasil Banco Mútiplo S.A.'>69 - BPN Brasil Banco Mútiplo S.A.</option>
<option value='70 - BRB - Banco de Brasília S.A.'>70 - BRB - Banco de Brasília S.A.</option>
<option value='72 - Banco Rural Mais S.A.'>72 - Banco Rural Mais S.A.</option>
<option value='73 - BB Banco Popular do Brasil S.A.'>73 - BB Banco Popular do Brasil S.A.</option>
<option value='74 - Banco J. Safra S.A.'>74 - Banco J. Safra S.A.</option>
<option value='75 - Banco CR2 S.A.'>75 - Banco CR2 S.A.</option>
<option value='76 - Banco KDB S.A.'>76 - Banco KDB S.A.</option>
<option value='96 - Banco BM&F de Serviços de Liquidação e Custódia S.A.'>96 - Banco BM&F de Serviços de Liquidação e Custódia S.A</option>
<option value='104 - Caixa Econômica Federal'>104 - Caixa Econômica Federal</option>
<option value='107 - Banco BBM S.A.'>107 - Banco BBM S.A.</option>
<option value='116 - Banco Único S.A.'>116 - Banco Único S.A.</option>
<option value='151 - Banco Nossa Caixa S.A.'>151 - Banco Nossa Caixa S.A.</option>
<option value='175 - Banco Finasa S.A.'>175 - Banco Finasa S.A.</option>
<option value='184 - Banco Itaú BBA S.A.'>184 - Banco Itaú BBA S.A.</option>
<option value='204 - Bankpar Banco Multiplo S.A.'>204 - Bankpar Banco Multiplo S.A.</option>
<option value='208 - Banco UBS Pactual S.A.'>208 - Banco UBS Pactual S.A.</option>
<option value='212 - Banco Matone S.A.'>212 - Banco Matone S.A.</option>
<option value='213 - Banco Arbi S.A.'>213 - Banco Arbi S.A.</option>
<option value='214 - Banco Dibens S.A.'>214 - Banco Dibens S.A.</option>
<option value='215 - Banco Comercial e de Investimento Sudameris S.A.'>215 - Banco Comercial e de Investimento Sudameris S.A.</option>
<option value='217 - Banco John Deere S.A.'>217 - Banco John Deere S.A.</option>
<option value='218 - Banco Bonsucesso S.A.'>218 - Banco Bonsucesso S.A.</option>
<option value='222 - Banco Calyon Brasil S.A.'>222 - Banco Calyon Brasil S.A.</option>
<option value='224 - Banco Fibra S.A.'>224 - Banco Fibra S.A.</option>
<option value='225 - Banco Brascan S.A.'>225 - Banco Brascan S.A.</option>
<option value='229 - Banco Cruzeiro do Sul S.A.'>229 - Banco Cruzeiro do Sul S.A.</option>
<option value='230 - Unicard Banco Múltiplo S.A.'>230 - Unicard Banco Múltiplo S.A.</option>
<option value='233 - Banco GE Capital S.A.'>233 - Banco GE Capital S.A.</option>
<option value='237 - Banco Bradesco S.A.'>237 - Banco Bradesco S.A.</option>
<option value='241 - Banco Clássico S.A.'>241 - Banco Clássico S.A.</option>
<option value='243 - Banco Máxima S.A.'>243 - Banco Máxima S.A.</option>
<option value='246 - Banco ABC Brasil S.A.'>246 - Banco ABC Brasil S.A.</option>
<option value='248 - Banco Boavista Interatlântico S.A.'>248 - Banco Boavista Interatlântico S.A.</option>
<option value='249 - Banco Investcred Unibanco S.A.'>249 - Banco Investcred Unibanco S.A.</option>
<option value='250 - Banco Schahin S.A.'>250 - Banco Schahin S.A.</option>
<option value='252 - Banco Fininvest S.A.'>252 - Banco Fininvest S.A.</option>
<option value='254 - Paraná Banco S.A.'>254 - Paraná Banco S.A.</option>
<option value='263 - Banco Cacique S.A.'>263 - Banco Cacique S.A.</option>
<option value='265 - Banco Fator S.A.'>265 - Banco Fator S.A.</option>
<option value='266 - Banco Cédula S.A.'>266 - Banco Cédula S.A.</option>
<option value='300 - Banco de La Nacion Argentina'>300 - Banco de La Nacion Argentina</option>
<option value='318 - Banco BMG S.A.'>318 - Banco BMG S.A.</option>
<option value='320 - Banco Industrial e Comercial S.A.'>320 - Banco Industrial e Comercial S.A.</option>
<option value='341 - Banco Itaú S.A.'>341 - Banco Itaú S.A.</option>
<option value='356 - Banco Real S.A.'>356 - Banco Real S.A.</option>
<option value='366 - Banco Société Générale Brasil S.A.'>366 - Banco Société Générale Brasil S.A.</option>
<option value='370 - Banco WestLB do Brasil S.A.'>370 - Banco WestLB do Brasil S.A.</option>
<option value='376 - Banco J. P. Morgan S.A.'>376 - Banco J. P. Morgan S.A.</option>
<option value='389 - Banco Mercantil do Brasil S.A.'>389 - Banco Mercantil do Brasil S.A.</option>
<option value='394 - Banco BMC S.A.'>394 - Banco BMC S.A.</option>
<option value='399 - HSBC Bank Brasil S.A.  - Banco Múltiplo'>399 - HSBC Bank Brasil S.A. - Banco Múltiplo</option>
<option value='409 - UNIBANCO - União de Bancos Brasileiros S.A.'>409 - UNIBANCO - União de Bancos Brasileiros S.A.</option>
<option value='412 - Banco Capital S.A.'>412 - Banco Capital S.A.</option>
<option value='422 - Banco Safra S.A.'>422 - Banco Safra S.A.</option>
<option value='453 - Banco Rural S.A.'>453 - Banco Rural S.A.</option>
<option value='456 - Banco de Tokyo-Mitsubishi UFJ Brasil S.A.'>456 - Banco de Tokyo-Mitsubishi UFJ Brasil S.A.</option>
<option value='464 - Banco Sumitomo Mitsui Brasileiro S.A.'>464 - Banco Sumitomo Mitsui Brasileiro S.A.</option>
<option value='477 - Citibank N.A.'>477 - Citibank N.A.</option>
<option value='479 - Banco ItaúBank S.A.'>479 - Banco ItaúBank S.A</option>
<option value='487 - Deutsche Bank S.A.  - Banco Alemão'>487 - Deutsche Bank S.A. - Banco Alemão</option>
<option value='488 - JPMorgan Chase Bank'>488 - JPMorgan Chase Bank</option>
<option value='492 - ING Bank N.V.'>492 - ING Bank N.V.</option>
<option value='494 - Banco de La Republica Oriental del Uruguay'>494 - Banco de La Republica Oriental del Uruguay</option>
<option value='495 - Banco de La Provincia de Buenos Aires'>495 - Banco de La Provincia de Buenos Aires</option>
<option value='505 - Banco Credit Suisse (Brasil) S.A.'>505 - Banco Credit Suisse (Brasil) S.A.</option>
<option value='600 - Banco Luso Brasileiro S.A.'>600 - Banco Luso Brasileiro S.A.</option>
<option value='604 - Banco Industrial do Brasil S.A.'>604 - Banco Industrial do Brasil S.A.</option>
<option value='610 - Banco VR S.A.'>610 - Banco VR S.A.</option>
<option value='611 - Banco Paulista S.A.'>611 - Banco Paulista S.A.</option>
<option value='612 - Banco Guanabara S.A.'>612 - Banco Guanabara S.A.</option>
<option value='613 - Banco Pecúnia S.A.'>613 - Banco Pecúnia S.A.</option>
<option value='623 - Banco Panamericano S.A.'>623 - Banco Panamericano S.A.</option>
<option value='626 - Banco Ficsa S.A.'>626 - Banco Ficsa S.A.</option>
<option value='630 - Banco Intercap S.A.'>630 - Banco Intercap S.A.</option>
<option value='633 - Banco Rendimento S.A.'>633 - Banco Rendimento S.A.</option>
<option value='634 - Banco Triângulo S.A.'>634 - Banco Triângulo S.A.</option>
<option value='637 - Banco Sofisa S.A.'>637 - Banco Sofisa S.A.</option>
<option value='638 - Banco Prosper S.A.'>638 - Banco Prosper S.A.</option>
<option value='641 - Banco Alvorada S.A.'>641 - Banco Alvorada S.A.</option>
<option value='643 - Banco Pine S.A.'>643 - Banco Pine S.A.</option>
<option value='652 - Banco Itaú Holding Financeira S.A.'>652 - Banco Itaú Holding Financeira S.A.</option>
<option value='653 - Banco Indusval S.A.'>653 - Banco Indusval S.A.</option>
<option value='654 - Banco A.J.Renner S.A.'>654 - Banco A.J.Renner S.A.</option>
<option value='655 - Banco Votorantim S.A.'>655 - Banco Votorantim S.A.</option>
<option value='707 - Banco Daycoval S.A.'>707 - Banco Daycoval S.A.</option>
<option value='719 - Banif-Banco Internacional do Funchal (Brasil)S.A.'>719 - Banif-Banco Internacional do Funchal (Brasil)S.A.</option>
<option value='721 - Banco Credibel S.A.'>721 - Banco Credibel S.A.</option>
<option value='724 - Banco Porto Seguro S.A.'>724 - Banco Porto Seguro S.A.</option>
<option value='734 - Banco Gerdau S.A.'>734 - Banco Gerdau S.A.</option>
<option value='735 - Banco Pottencial S.A.'>735 - Banco Pottencial S.A.</option>
<option value='738 - Banco Morada S.A.'>738 - Banco Morada S.A.</option>
<option value='739 - Banco BGN S.A.'>739 - Banco BGN S.A.</option>
<option value='740 - Banco Barclays S.A.'>740 - Banco Barclays S.A.</option>
<option value='741 - Banco Ribeirão Preto S.A.'>741 - Banco Ribeirão Preto S.A.</option>
<option value='743 - Banco Semear S.A.'>743 - Banco Semear S.A.</option>
<option value='744 - BankBoston N.A.'>744 - BankBoston N.A.</option>
<option value='745 - Banco Citibank S.A.'>745 - Banco Citibank S.A.</option>
<option value='746 - Banco Modal S.A.'>746 - Banco Modal S.A.</option>
<option value='747 - Banco Rabobank International Brasil S.A.'>747 - Banco Rabobank International Brasil S.A.</option>
<option value='748 - Banco Cooperativo Sicredi S.A.'>748 - Banco Cooperativo Sicredi S.A.</option>
<option value='749 - Banco Simples S.A.'>749 - Banco Simples S.A.</option>
<option value='751 - Dresdner Bank Brasil S.A.  - Banco Múltiplo'>751 - Dresdner Bank Brasil S.A. - Banco Múltiplo</option>
<option value='752 - Banco BNP Paribas Brasil S.A.'>752 - Banco BNP Paribas Brasil S.A.</option>
<option value='753 - Banco Comercial Uruguai S.A.'>753 - Banco Comercial Uruguai S.A.</option>
<option value='755 - Banco Merrill Lynch de Investimentos S.A.'>755 - Banco Merrill Lynch de Investimentos S.A.</option>
<option value='756 - Banco Cooperativo do Brasil S.A.  - BANCOOB'>756 - Banco Cooperativo do Brasil S.A. - BANCOOB</option>
<option value='757 - Banco KEB do Brasil S.A.'>757 - Banco KEB do Brasil S.A.</option>
<option value='--- Banco Bankpar S.A.'>--- Banco Bankpar S.A.</option>
<option value='--- Banco Fiat S.A.'>--- Banco Fiat S.A.</option>
<option value='--- BES Investimento do Brasil S.A. -Banco de Investimento'>--- BES Investimento do Brasil S.A.-Banco de Investimento</option>
<option value='--- Banco de Lage Landen Brasil S.A.'>--- Banco de Lage Landen Brasil S.A.</option>
<option value='--- Banco GMAC S.A.'>--- Banco GMAC S.A.</option>
<option value='--- Banco Citicard S.A.'>--- Banco Citicard S.A.</option>
<option value='--- Banco Itaucred Financiamentos S.A.'>--- Banco Itaucred Financiamentos S.A.</option>
<option value='--- Banco IBM S.A.'>--- Banco IBM S.A.</option>
<option value='--- Banco Volkswagen S.A.'>--- Banco Volkswagen S.A.</option>
<option value='--- Banco Moneo S.A.'>--- Banco Moneo S.A.</option>
<option value='--- Banco Maxinvest S.A.'>--- Banco Maxinvest S.A.</option>
<option value='--- Banco Tricury S.A.'>--- Banco Tricury S.A.</option>
<option value='--- Banco BRJ S.A.'>--- Banco BRJ S.A.</option>
<option value='--- Banco Rodobens S.A.'>--- Banco Rodobens S.A.</option>
<option value='--- Banco Ourinvest S.A.'>--- Banco Ourinvest S.A.</option>
<option value='--- Banco Ford S.A.'>--- Banco Ford S.A.</option>
<option value='--- Banco CNH Capital S.A.'>--- Banco CNH Capital S.A.</option>
<option value='--- Banco Toyota do Brasil S.A.'>--- Banco Toyota do Brasil S.A.</option>
<option value='--- Banco Daimlerchrysler S.A.'>--- Banco Daimlerchrysler S.A.</option>
<option value='--- Banco Honda S.A.'>--- Banco Honda S.A.</option>
<option value='--- Banco Volvo (Brasil) S.A.'>--- Banco Volvo (Brasil) S.A.</option>
<option value='--- Banco PSA Finance Brasil S.A.'>--- Banco PSA Finance Brasil S.A.</option>
<option value='019-1  - Banco Azteca do Brasil S.A.'>019-1  - Banco Azteca do Brasil S.A.</option>
<option value=' - Banco Carrefour S.A.'> - Banco Carrefour S.A.</option>